[project]
name = "incode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lxml>=6.0.0",
    "pydantic>=2.11.7",
    "requests>=2.32.4",
]
